version: '3.4'

services:
  samba:
    image: elswork/samba:armv7l
    environment:
      TZ: 'Europe/Madrid'
    networks:
      - default
    ports:
      - "445:445"
    restart: unless-stopped
    volumes:
      - /home/pirate/docker/makefile:/share/folder
      #- /path/to/be/shared:/share/folder
    command: '-u "$(id -u):$(id -g):$(id -un):$(id -gn):put-any-password-here" -s "SmbShare:/share/folder:rw:$(id -un)"'

networks:
  default: